"""add deposit created_at

Revision ID: 2b1af5c0babf
Revises: 5679798edf27
Create Date: 2026-09-27 15:33:23.972404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1af5c0babf'
down_revision: Union[str, Sequence[str], None] = '5679798edf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposits', 'created_at')
    # ### end Alembic commands ###
