"""initial schema

Revision ID: 5679798edf27
Revises: 
Create Date: 2026-09-27 14:45:07.806549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5679798edf27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_cursor',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('last_block', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_table('tax_defaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('income_type', sa.String(), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'income_type', name='uq_tax_default_country_income_type')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('privy_id', sa.String(), nullable=False),
    sa.Column('wallet', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet')
    )
    op.create_index(op.f('ix_users_privy_id'), 'users', ['privy_id'], unique=True)
    op.create_table('vaults',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vault_addr', sa.String(), nullable=False),
    sa.Column('income_inbox', sa.String(), nullable=False),
    sa.Column('topup_inbox', sa.String(), nullable=False),
    sa.Column('payout_addr', sa.String(), nullable=False),
    sa.Column('deployed_tx', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('income_inbox'),
    sa.UniqueConstraint('topup_inbox'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('vault_addr')
    )
    op.create_table('bills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_vault_id'), 'bills', ['vault_id'], unique=False)
    op.create_table('bucket_balances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('as_of_block', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id', 'bucket', name='uq_bucket_balance_vault_bucket')
    )
    op.create_index(op.f('ix_bucket_balances_vault_id'), 'bucket_balances', ['vault_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('proposed', sa.JSON(), nullable=False),
    sa.Column('policy_result', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_decisions_vault_id'), 'decisions', ['vault_id'], unique=False)
    op.create_index('ix_decisions_vault_id_created_at', 'decisions', ['vault_id', 'created_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('run_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('income_low', sa.Double(), nullable=False),
    sa.Column('income_mid', sa.Double(), nullable=False),
    sa.Column('income_high', sa.Double(), nullable=False),
    sa.Column('needed', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_vault_id'), 'forecasts', ['vault_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_vault_id'), 'goals', ['vault_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_integrations_vault_id'), 'integrations', ['vault_id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('default_kind', sa.String(), nullable=False),
    sa.Column('known_sources', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id')
    )
    op.create_table('tax_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('rate_bps', sa.Integer(), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('source_default_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_default_id'], ['tax_defaults.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_id')
    )
    op.create_table('integration_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', 'tx_hash', name='uq_integration_event_tx_hash')
    )
    op.create_index(op.f('ix_integration_events_integration_id'), 'integration_events', ['integration_id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vault_id', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('kind_source', sa.String(), nullable=False),
    sa.Column('integration_event_id', sa.String(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_event_id'], ['integration_events.id'], ),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'log_index', name='uq_deposit_tx_log_index')
    )
    op.create_index(op.f('ix_deposits_vault_id'), 'deposits', ['vault_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deposit_id', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_deposit_id'), 'allocations', ['deposit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_deposit_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_deposits_vault_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_integration_events_integration_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_table('tax_settings')
    op.drop_table('rules')
    op.drop_index(op.f('ix_integrations_vault_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_goals_vault_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_forecasts_vault_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_decisions_vault_id_created_at', table_name='decisions')
    op.drop_index(op.f('ix_decisions_vault_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_bucket_balances_vault_id'), table_name='bucket_balances')
    op.drop_table('bucket_balances')
    op.drop_index(op.f('ix_bills_vault_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_users_privy_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tax_defaults')
    op.drop_table('indexer_cursor')
    # ### end Alembic commands ###
